
import React from 'react';
import { motion } from 'framer-motion';
import './Gallery.css';
import galleryData from './galleryData.json';

const Gallery = () => {
    // Use the data from the JSON file generated by the script
    const images = galleryData || [];

    return (
        <div className="gallery-container">
            <h2>Nuestros Recuerdos</h2>
            <div className="gallery-grid">
                {images.map((filename, index) => (
                    <motion.div
                        key={index}
                        className="gallery-item"
                        initial={{ opacity: 0, y: 20 }}
                        whileInView={{ opacity: 1, y: 0 }}
                        viewport={{ once: true }}
                        transition={{ duration: 0.5, delay: index * 0.05 }} // Stagger effect
                        whileHover={{ scale: 1.05, zIndex: 10 }}
                    >
                        <img
                            src={`/gallery/${filename}`}
                            alt={`Recuerdo ${index + 1}`}
                            onError={(e) => { e.target.style.display = 'none' }} // Hide if not found
                        />
                    </motion.div>
                ))}
            </div>
        </div>
    );
};

export default Gallery;
